// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ScheduleMixer.Shared.Core.Json;
//
//    var ingredient = Ingredient.FromJson(jsonString);

namespace ScheduleMixer.Shared.Core.Json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Ingredient
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("cost")]
        public long Cost { get; set; }

        [JsonProperty("baseEffect")]
        public string BaseEffect { get; set; }

        [JsonProperty("replacements")]
        public Dictionary<string, string> Replacements { get; set; }
    }

    public partial class Ingredient
    {
        public static List<Ingredient> FromJson(string json) => JsonConvert.DeserializeObject<List<Ingredient>>(json, ScheduleMixer.Shared.Core.Json.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Ingredient> self) => JsonConvert.SerializeObject(self, ScheduleMixer.Shared.Core.Json.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
